### ISSUE TITLE
Invalid response from route /api/tweets: handler should return a Response object

### ISSUE THREAD

**Issue by markholdex** [holdex/holdex-venture-studio#349] opened 2023-06-08 15:10 UTC
View details in Rollbar: [https://rollbar.com/holdex/Holdex/items/4431/](https://rollbar.com/holdex/Holdex/items/4431/)

```
Invalid response from route /api/tweets: handler should return a Response object
```

**Comment by zolotokrylin** [comment] 2023-07-17 05:40
caused by #313

**Comment by georgeciubotaru** [comment] 2023-07-18 05:22
@zolotokrylin `api/tweets` it's not used anymore, we can `backlog` this issue

**Comment by zolotokrylin** [comment] 2023-07-18 05:41
@georgeciubotaru you mean we can close it (or delete it)?

**Comment by georgeciubotaru** [comment] 2023-07-18 05:45
@zolotokrylin better to close it

**Closed** 2023-07-18 05:48 UTC
Labels: bug
