### ISSUE TITLE
Problem: AutoInvoice app not displaying all submitted PRs

### ISSUE THREAD

**Issue by surajsharma** [holdex/holdex-venture-studio#520] opened 2023-09-12 07:47 UTC
> Create it in Holdex repo and also mention that you are lacking access

<img width="1049" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/5298624/4ab52982-5b2d-40d6-b71d-26ad7e1ee074">

**Comment by georgeciubotaru** [comment] 2023-09-12 08:12
@surajsharma  Please rename the issue accordingly. 
From your screenshot, I can see you have submitted PRs displayed.

**Comment by surajsharma** [comment] 2023-09-12 08:14
> @surajsharma Please rename the issue accordingly. From your screenshot, I can see you have submitted PRs displayed.

@georgeciubotaru suggest me a good PR title, i cannot understand what to write, it is showing only one submitted PR but I have many

**Comment by zolotokrylin** [comment] 2023-09-12 10:25
@georgeciubotaru Are we missing PRs?

**Comment by georgeciubotaru** [comment] 2023-09-13 07:41
@zolotokrylin, @surajsharma The issue is acknowledged, and will be fixed soon.

**Comment by power-f-GOD** [comment] 2023-09-13 07:48
🤔 @surajsharma , is this still an issue for you, 'cause I can see my PRs.

**Comment by surajsharma** [comment] 2023-09-13 07:51
> 🤔 @surajsharma , is this still an issue for you, 'cause I can see my PRs.

@power-f-GOD yes the tool is behaving strangely on my end, today there are even fewer PRs than yestderday

**Comment by georgeciubotaru** [comment] 2023-09-13 07:53
@surajsharma you have 5 PRs in the database
 Two are closed (you should see them in the UI)
 Three are not closed and you cannot see them until you they will be merged

**Comment by power-f-GOD** [comment] 2023-09-13 07:56
> 🤔 @surajsharma , is this still an issue for you, 'cause I can see my PRs.

my **CLOSED** PRs, BTW.🌚

**Comment by power-f-GOD** [comment] 2023-09-13 07:59
You have only one closed PR (from the DB) though.

Which is the other closed PR that you think is not being returned?

**Comment by georgeciubotaru** [comment] 2023-09-13 08:01
@power-f-GOD 
https://autoinvoice-theta.vercel.app/contributors/surajsharma

**Comment by surajsharma** [comment] 2023-09-13 08:01
> You have only one closed PR (from the DB) though.
> 
> Which is the other closed PR that you think is not being returned?

this one https://github.com/holdex/holdex-venture-studio/pull/496 was submitted using the tool

**Comment by power-f-GOD** [comment] 2023-09-13 08:07
> @power-f-GOD https://autoinvoice-theta.vercel.app/contributors/surajsharma

Ok. That is wrong. It doesn't take account of closed PRs (just submitted), which is now fixed in the `new implementation`.

> this one https://github.com/holdex/holdex-venture-studio/pull/496 was submitted using the tool

@georgeciubotaru , so it seems it wasn't updated in the DB when the event occurred. My guess is that it happened when the webhook failed due to the validation thingy last week (I may be wrong).

**Comment by georgeciubotaru** [comment] 2023-09-13 10:06
@surajsharma Can please confirm if the issue is fixed?

**Comment by surajsharma** [comment] 2023-09-13 10:15
@georgeciubotaru no, now i am seeing other people's prs in my list
<img width="724" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/5298624/93aa7e44-d088-46f9-9926-973cfc7aab09">

**Comment by georgeciubotaru** [comment] 2023-09-13 10:22
@power-f-GOD

**Comment by power-f-GOD** [comment] 2023-09-13 10:35
@surajsharma 

Request:
```
invoice.holdex.io/api/items?contributor_id=5298624 // this is your ID
```

Response:
```json
{
    "data": [
        {
            "_id": "64f19ad2ff3bdfca601f4a6d",
            "id": 1485985740,
            "merged": true,
            "org": "holdex",
            "owner": "surajsharma",
            "repo": "holdex-venture-studio",
            "title": "feat: navbar redesign",
            "type": "pull_request",
            "url": "https://api.github.com/repos/holdex/holdex-venture-studio/pulls/499",
            "experience": "positive",
            "hours": "5",
            "submitted": true,
            "closed_at": "2023-09-06T09:17:43Z",
            "contributor_ids": [
                8217518,
                5298624
            ],
            "created_at": "2023-08-23T08:30:02Z",
            "updated_at": "2023-09-06T09:17:28Z",
            "submission_ids": [],
            "owner_id": 5298624
        }
    ]
}
```

Please, refresh the app and try again and see if it persists. 

Also, help me inspect the network tab and see the response.

**Comment by georgeciubotaru** [comment] 2023-09-13 10:46
@power-f-GOD Actually the current production code contains `https://invoice.holdex.io/api/items?contributor=surajsharma`

**Comment by power-f-GOD** [comment] 2023-09-13 10:52
> https://invoice.holdex.io/api/items?contributor=surajsharma

Ah. I see it. The issue is fixed in this PR: https://github.com/holdex/autoinvoice/pull/134

**Comment by surajsharma** [comment] 2023-09-14 04:04
> > [invoice.holdex.io/api/items?contributor=surajsharma](https://invoice.holdex.io/api/items?contributor=surajsharma)
> 
> Ah. I see it. The issue is fixed (or update is made) in this PR: [holdex/autoinvoice/pull/134](https://github.com/holdex/autoinvoice/pull/134)

i'm not in the repo so idk, here https://invoice.holdex.io/api/items?owner=surajsharma%EF%BF%BC the data block is empty

**Comment by surajsharma** [comment] 2023-09-14 16:20
@all any updates?

**Comment by power-f-GOD** [comment] 2023-09-15 04:14
> i'm not in the repo so idk,

I meant that it would have been fixed when that PR is merged.

> no, now i am seeing other people's prs in my list

Are you still experiencing this?

@surajsharma

**Comment by surajsharma** [comment] 2023-09-15 04:27
> Are you still experiencing this?
> 
> @surajsharma

@power-f-GOD yes


the submitted prs section is empty whereas i have submitted prs previously

**Closed** 2023-09-18 11:13 UTC

**Comment by power-f-GOD** [comment] 2023-09-18 12:43
BTW, FYI, @surajsharma , this should have been fixed now.✅

PS. Also updated the `merge` state of the PR in question.
