### ISSUE TITLE
Problem: JetBrains is not published on our site

### ISSUE THREAD

**Issue by almon-s** [holdex/holdex-venture-studio#491] opened 2023-08-14 08:42 UTC
We need to publish the article for JetBrains asap
```[tasklist]
### Tasks
- [ ] https://github.com/holdex/holdex-venture-studio/issues/11
```

**Comment by zolotokrylin** [comment] 2023-08-15 13:54
Duplicate of https://github.com/holdex/holdex-venture-studio/issues/11

**Closed** 2023-08-15 14:10 UTC
Labels: value: high
