### ISSUE TITLE
Problem: Bullet points are not being displayed correctly

### ISSUE THREAD

**Issue by almon-s** [holdex/holdex-venture-studio#357] opened 2023-06-12 03:42 UTC
Problem: Bullet points are not being displayed correctly

_Originally posted by @almon-s in https://github.com/holdex/operations/issues/77#issuecomment-1586526723_
            
Doc
<img width="664" alt="Screenshot 2023-06-12 at 10 54 19 AM" src="https://github.com/holdex/holdex-venture-studio/assets/112711034/b83100c6-3b02-40ca-9402-87a377a442ba">

[Article](https://holdex.io/c/learn/holdex-hr-guidelines)
<img width="628" alt="Screenshot 2023-06-12 at 10 56 16 AM" src="https://github.com/holdex/holdex-venture-studio/assets/112711034/2499d99c-8e12-4503-a68e-03aaa4ce0232">

**Comment by zolotokrylin** [comment] 2023-06-12 05:35
duplicate of https://github.com/holdex/holdex-venture-studio/issues/225

**Closed by zolotokrylin** 2023-06-12 05:35 UTC
Labels: bug
