### ISSUE TITLE
Problem: contrast of UI elements is wrong (accessibility)

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#459] opened 2023-07-17 04:26 UTC
![image](https://github.com/holdex/holdex-venture-studio/assets/1125014/e49b7ccd-4d93-444b-a5b9-1f3306b15a2a)

@predrag-us please check this issue across the whole interface and components. Thanks

---

Solution: Make sure the green color is changed and adapted to the light theme. 

# [Figma Design](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/Holdex?type=design&node-id=391-2491&mode=design&t=mgLQ6N7GGXW1C90c-4)

**Comment by predrag-us** [comment] 2023-07-17 08:25
@zolotokrylin 

Wrong implementation. It's like this by design:

<img width="1204" alt="CleanShot 2023-07-17 at 10 07 57@2x" src="https://github.com/holdex/holdex-venture-studio/assets/18451941/47b532ad-b87b-4913-970d-d0538ad8f8f4">

**Comment by winter-sols** [comment] 2023-07-17 15:34
@markcurchin Okay, thank you for sharing.

**Comment by winter-sols** [comment] 2023-07-17 16:04
@zolotokrylin @markcurchin 
Can you share the design?
I am not sure how should it look like?

**Comment by winter-sols** [comment] 2023-07-17 16:18
@markcurchin Where can I find the page?

**Comment by winter-sols** [comment] 2023-07-17 18:34
@markholdex Thank you for sharing

**Comment by winter-sols** [comment] 2023-07-18 09:36
@markholdex 
I can't find the chart on my local.

**Comment by winter-sols** [comment] 2023-07-18 10:37
@georgeciubotaru 
I can't see the charts
![Screenshot 2023-07-18 193656](https://github.com/holdex/holdex-venture-studio/assets/100481931/842c618f-0b00-4311-9b5a-e1af5879259e)

**Comment by winter-sols** [comment] 2023-07-18 10:45
@markholdex @georgeciubotaru 
Could you join a quick call and show me?

**Comment by georgeciubotaru** [comment] 2023-07-18 11:04
@winter-sols try this one `http://localhost:3000/c/elysio/testing-startup-chart`

**Comment by winter-sols** [comment] 2023-07-19 09:57
@predrag-us @georgeciubotaru 
I still can't find it. The issue is to fix the color, but I can't find.
![image](https://github.com/holdex/holdex-venture-studio/assets/100481931/de91e006-3709-4855-b9f1-95858c7209f5)

Please help me out. Once I learn the rope, I am sure everything will be straightforward.
Thank you

**Comment by georgeciubotaru** [comment] 2023-07-19 10:45
@winter-sols 
![image](https://github.com/holdex/holdex-venture-studio/assets/8217518/ff1c5a5c-1470-438f-803a-cdb639d9cc00)

**Comment by winter-sols** [comment] 2023-07-19 11:33
on my local
![image](https://github.com/holdex/holdex-venture-studio/assets/100481931/7b734dfb-fa1c-4a7c-84ab-ce726337819a)

**Comment by winter-sols** [comment] 2023-07-19 12:43
@georgeciubotaru Yeah, I can see it now.
@markholdex @predrag-us  If you see the 3 images, things will be clear. According to my local, the color is implemented as designed.
I get the color on my local
![Screenshot 2023-07-19 153509](https://github.com/holdex/holdex-venture-studio/assets/100481931/37f17fac-f097-4a52-9bea-f9dc94c5b8c9)
And converted it to hex
![Screenshot 2023-07-19 153539](https://github.com/holdex/holdex-venture-studio/assets/100481931/cb9aff62-199e-4c19-a3c6-75422b86282a)
The result show that it is the same as the design
![Screenshot 2023-07-19 153753](https://github.com/holdex/holdex-venture-studio/assets/100481931/cc0bf705-ec59-493b-9da5-bcd6fd73b5b7)

**Comment by predrag-us** [comment] 2023-07-19 12:51
@winter-sols Maybe, for some reason, there's a difference on some breakpoints, so please check that. Otherwise, everything looks as it should on the screenshots.

**Comment by winter-sols** [comment] 2023-07-19 13:01
@predrag-us 
I checked it in different breakpoints
![Screenshot 2023-07-19 155906](https://github.com/holdex/holdex-venture-studio/assets/100481931/342840ee-26ad-4562-97dc-2ce1ecd9f7f6)
![Screenshot 2023-07-19 155933](https://github.com/holdex/holdex-venture-studio/assets/100481931/61d7cdba-9ef6-4051-918a-484229e1faeb)
![Screenshot 2023-07-19 155957](https://github.com/holdex/holdex-venture-studio/assets/100481931/d19517c2-bcb2-4636-a641-8b050cda92a6)
![Screenshot 2023-07-19 160030](https://github.com/holdex/holdex-venture-studio/assets/100481931/e867c0ef-028f-46d0-8724-7580f9d7eed3)

**Comment by winter-sols** [comment] 2023-07-19 13:02
Can you specify the case?

**Comment by predrag-us** [comment] 2023-07-19 13:05
@zolotokrylin 

Can you please check if the problem is persistent on your side? 
I just double-checked on my side (both computer and phone, multiple browsers) and everywhere is as it should be.

cc: @winter-sols

**Comment by zolotokrylin** [comment] 2023-07-20 07:33
@predrag-us if it is working correctly on your side, then it must work correctly on my side. We are looking at the same site. If you are confident the issue is resolved, please close it.
I can't test it on my side, because all chards are red (down).

**Comment by zolotokrylin** [comment] 2023-07-20 07:35
Just make sure the contrast is appropriate in the design and then in the app.

**Comment by predrag-us** [comment] 2023-07-20 07:41
@winter-sols Please search for all instances of green on light mode and make sure we're using the correct shade of green. If there're mistakes, please fix them. If everything is okay, please confirm so I can close the issue. Thanks!

**Comment by predrag-us** [comment] 2023-07-20 08:22
All good ⏤ this issue can safely be closed. 
I don't have the option to close this issue, unsure why. If anyone of you has the option to close it, please do.
cc: @markholdex @georgeciubotaru

<img width="296" alt="CleanShot 2023-07-20 at 10 20 52@2x" src="https://github.com/holdex/holdex-venture-studio/assets/18451941/83e592a5-52c9-45fb-9850-54c93fd284fe">

**Closed** 2023-07-20 08:45 UTC
Labels: bug
