### ISSUE TITLE
Problem: browser doesn't remember my color scheme preference

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#386] opened 2023-06-14 17:34 UTC
# Problem
When I refresh browser it defaults to light color scheme, even if I selected dark one before the refresh

# Solution
Two ACs: 
- take into account user's OS preference setting https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
- when the UI theme switcher is used, remember the setting in the browser cookie (or similar)

To be resolved in a separate PR (not in this one).

_Originally posted by @zolotokrylin in https://github.com/holdex/holdex-venture-studio/issues/381#issuecomment-1591708302_

**Comment by power-f-GOD** [comment] 2023-06-15 17:04
In coding...👩🏽‍💻⏳

**Comment by power-f-GOD** [comment] 2023-06-16 02:14
Although I'm done with this, there's a little/subtle issue that I spent some time trying to fix (and tried all workarounds in my arsenal), but to no avail.💔

So, the issue is what I would call a **FODT** (Flash Of Default Theme).

What happens is that, on reload of the page, the initial/first theme set is the default theme (which is `dark` or the user's OS's theme). At this instant (per my investigation), the `data-theme="<mode>"` attribute isn't set on the `body` element, hence it falls back to using the `@media (prefers-color-scheme: <mode>)`.

Ultimately, per my investigation, this seems to "not be fixable", because, of course, the feature requires JavaScript to work, so until the JavaScript (needed) is loaded, parsed, and then executed by the browser, nothing will happen. And taking a look at the Network tab in Dev Tools, there's a ton of JS being loaded, hence the **FODT** is inevitable.💔

Hopefully, in prod, the flash is minimized (since the JS may be optimized), but I doubt it would completely remove it or fix the issue.

PS. I don't think creating a Problem Statement for this is needed since, like I said,  'this seems to "not be fixable"'.

Yeah, that's it. Will make a PR as soon as #395 gets merged.✔

That will be all for now, guys.✌🏼 It's been a week.😎

**Comment by surajsharma** [comment] 2023-06-16 07:59
@power-f-GOD @zolotokrylin intrigued by this issue, if needed we could look at something like this https://github.com/beynar/svelte-themes which promises an override

**Comment by zolotokrylin** [comment] 2023-06-16 10:02
Interesting 🧐 
The fastest way to resolve this Problem would be the best in our case. Leaving it up to Power to choose the way.

**Comment by power-f-GOD** [comment] 2023-06-16 10:50
Hi, @surajsharma . Thanks for the suggestion.💕 I'll have a look at it in a moment.🤲🏼

@zolotokrylin , 😌 All right. 🙌🏼🙇🏽‍♂️

**Comment by power-f-GOD** [comment] 2023-06-16 11:58
Ok. So, I've fixed the issue!🥵😅 

The resource @surajsharma suggested was helpful.🙌🏼 

I cloned the repo, and took a look at their implementation; it is quite a clever one💡, even though from a security perspective it may not be the best, but, for now, it works.✅

So, what they did was embed a `script` via a string literal in the `head` element (which certainly would run before all other scripts that will be loaded eventually). And not only that, they also targetted the `root` element which is the `html` element, since the `body` element, from my investigation, at the instant when the embedded `script` is executed, is `null` or not mounted.📝

Will make a PR as soon as #395 gets merged.✔️

**Comment by surajsharma** [comment] 2023-06-16 12:07
@power-f-GOD way to go @power-f-GOD  🙌

**Closed** 2023-06-16 16:18 UTC
Labels: enhancement
